name: jupyterlab-ide
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - ipywidgets
  - pip
  - jupyterlab >= 3.0
  - pyyaml # for postBuild script
  - jupyterlab-unfold # https://github.com/jupyterlab-contrib/jupyterlab-unfold
  - jupyterlab-lsp # https://github.com/jupyter-lsp/jupyterlab-lsp
  - jupyterlab-git # https://github.com/jupyterlab/jupyterlab-git
  - jupyterlab-variableinspector # https://github.com/lckr/jupyterlab-variableInspector
  - jupyterlab-spellchecker # https://github.com/jupyterlab-contrib/spellchecker
  - pip:
    - black
    - isort
    - yapf
    - autopep8
    - jupyterlab-code-formatter #https://github.com/ryantam626/jupyterlab_code_formatter
    - jedi-language-server
    - jupyterlab-vim # https://github.com/jupyterlab-contrib/jupyterlab-vim








