name: jupyterlab-ide
channels:
  - conda-forge
  - krinsman # jupyterlab_html
  - defaults
dependencies:
  - jupyterlab >= 3.0
  - pyyaml # for postBuild script
  - jupyterlab-unfold # https://github.com/jupyterlab-contrib/jupyterlab-unfold
  - jupyterlab_html # https://github.com/QuantStack/jupyterlab-drawio
  - jupyterlab-lsp # https://github.com/jupyter-lsp/jupyterlab-lsp
  - jupyterlab-git # https://github.com/jupyterlab/jupyterlab-git
  - jupyterlab-variableinspector # https://github.com/lckr/jupyterlab-variableInspector
